import Foundation

/// A testable target entry used for auto-generated test plans in Geko.
///
/// Wraps a ``TestableTarget`` with optional test filtering (selected/skipped tests).
/// Conforms to `ExpressibleByStringInterpolation`, so you can use a plain string
/// wherever an `AutogeneratedTestableTarget` is expected:
///
/// ```swift
/// let targets: [AutogeneratedTestableTarget] = [
///     "MyFeatureTests",
///     .target("MyOtherTests", skippedTests: ["MyOtherTests/testFlaky"]),
/// ]
/// ```
// public struct AutogeneratedTestableTarget: Codable, Equatable, Sendable, ExpressibleByStringInterpolation {
//     /// The underlying testable target reference that identifies
//     /// which target should be included in the generated test plan.
//     public let target: TestableTarget
//     /// A list of specific tests to include in the plan.
//     ///
//     /// Each entry uses the Xcode test identifier format, e.g.
//     /// `"MyTests/testExample"` or `"MyTests"` for an entire suite.
//     /// When non-empty, only these tests will be executed for this target.
//     /// An empty array means all tests are included (subject to `skippedTests`).
//     public let selectedTests: [String]
//     /// A list of specific tests to exclude from the plan.
//     ///
//     /// Each entry uses the Xcode test identifier format, e.g.
//     /// `"MyTests/testExample"` or `"MyTests"` for an entire suite.
//     /// These tests will be skipped even if they would otherwise run.
//     /// An empty array means no tests are skipped.
//     public let skippedTests: [String]
//
//     public init(
//         _ target: TestableTarget,
//         selectedTests: [String] = [],
//         skippedTests: [String] = [],
//     ) {
//         self.target = target
//         self.selectedTests = selectedTests
//         self.skippedTests = skippedTests
//     }
//
//     public init(stringLiteral value: String) {
//         self.init(TestableTarget(stringLiteral: value))
//     }
//
//     /// Creates an ``AutogeneratedTestableTarget`` with optional test filtering.
//     ///
//     /// This factory method provides a more readable call-site syntax:
//     /// ```swift
//     /// .target("MyTests", selectedTests: ["MyTests/testImportant"])
//     /// ```
//     ///
//     /// - Parameters:
//     ///   - target: The testable target to include.
//     ///   - selectedTests: Tests to run exclusively. Empty means run all.
//     ///   - skippedTests: Tests to skip. Empty means skip none.
//     /// - Returns: A configured ``AutogeneratedTestableTarget``.
//     public static func target(
//         _ target: TestableTarget,
//         selectedTests: [String] = [],
//         skippedTests: [String] = [],
//     ) -> Self {
//         .init(target, selectedTests: selectedTests, skippedTests: skippedTests)
//     }
// }
//
