import Foundation

@frozen
public enum AutogeneratedSchemes: Codable, Equatable {
    public struct AutogeneratedSchemeWorkspace: Codable, Equatable {
        /// Contains options for code coverage
        @frozen
        public enum CodeCoverageMode: Codable, Equatable {
            /// Gather code coverage data for all targets in workspace.
            case all
            /// Enable code coverage for targets that have enabled code coverage in any of schemes in workspace.
            case relevant
            /// Gather code coverage for specified target references.
            case targets([TargetReference])
            /// Do not gather code coverage data.
            case disabled
        }

        public let platform: Platform
        public let productFilters: [Product]
        public let onlyFocusedTargets: Bool
        public let suffix: String?
        public let testActionArguments: Arguments?
        public let codeCoverageMode: CodeCoverageMode
        public let testingOptions: TestingOptions
        public let testLanguage: SchemeLanguage?
        public let testRegion: String?
        public let testScreenCaptureFormat: ScreenCaptureFormat?

        public init(
            platform: Platform,
            productFilters: [Product],
            onlyFocusedTargets: Bool,
            suffix: String?,
            testActionArguments: Arguments?,
            codeCoverageMode: CodeCoverageMode,
            testingOptions: TestingOptions,
            testLanguage: SchemeLanguage?,
            testRegion: String?,
            testScreenCaptureFormat: ScreenCaptureFormat?
        ) {
            self.platform = platform
            self.productFilters = productFilters
            self.onlyFocusedTargets = onlyFocusedTargets
            self.testActionArguments = testActionArguments
            self.suffix = suffix
            self.codeCoverageMode = codeCoverageMode
            self.testingOptions = testingOptions
            self.testLanguage = testLanguage
            self.testRegion = testRegion
            self.testScreenCaptureFormat = testScreenCaptureFormat
        }
    }

    public struct AutogeneratedSchemeProject: Codable, Equatable {
        @frozen
        public enum TargetSchemesGrouping: Codable, Equatable {
            /// Generate a single scheme for each project.
            case singleScheme

            /// Group schemes according to the suffix of their names.
            case byNameSuffix(build: Set<String>, test: Set<String>, run: Set<String>)

            /// Group the targets by local pods. 1 build+test (required), n app (optional)
            case pods

            /// Generate a scheme for each target.
            case notGrouped
        }

        public let onlyFocusedTargets: Bool
        public let suffix: String?
        public let exceptRegexps: [String]
        public let testActionArguments: Arguments?
        public let runActionArguments: Arguments?
        public let targetSchemesGrouping: TargetSchemesGrouping
        public let codeCoverageEnabled: Bool
        public let testingOptions: TestingOptions
        public let testLanguage: SchemeLanguage?
        public let testRegion: String?
        public let testScreenCaptureFormat: ScreenCaptureFormat?
        public let runLanguage: SchemeLanguage?
        public let runRegion: String?
        public let testPlans: [String]

        public init(
            onlyFocusedTargets: Bool,
            suffix: String?,
            exceptRegexps: [String],
            testActionArguments: Arguments?,
            runActionArguments: Arguments?,
            targetSchemesGrouping: TargetSchemesGrouping,
            codeCoverageEnabled: Bool,
            testingOptions: TestingOptions,
            testLanguage: SchemeLanguage?,
            testRegion: String?,
            testScreenCaptureFormat: ScreenCaptureFormat?,
            runLanguage: SchemeLanguage?,
            runRegion: String?,
            testPlans: [String]
        ) {
            self.onlyFocusedTargets = onlyFocusedTargets
            self.suffix = suffix
            self.exceptRegexps = exceptRegexps
            self.testActionArguments = testActionArguments
            self.runActionArguments = runActionArguments
            self.targetSchemesGrouping = targetSchemesGrouping
            self.codeCoverageEnabled = codeCoverageEnabled
            self.testingOptions = testingOptions
            self.testLanguage = testLanguage
            self.testRegion = testRegion
            self.testScreenCaptureFormat = testScreenCaptureFormat
            self.runLanguage = runLanguage
            self.runRegion = runRegion
            self.testPlans = testPlans
        }
    }

    case workspace(AutogeneratedSchemeWorkspace)
    case allProjects(AutogeneratedSchemeProject)
    case project(projectName: String, AutogeneratedSchemeProject)

    public static func workspace(
        platform: Platform,
        productFilters: [Product] = [],
        onlyFocusedTargets: Bool = true,
        suffix: String? = nil,
        testActionArguments: Arguments? = nil,
        codeCoverageMode: AutogeneratedSchemeWorkspace.CodeCoverageMode = .disabled,
        testingOptions: TestingOptions = [],
        testLanguage: SchemeLanguage? = nil,
        testRegion: String? = nil,
        testScreenCaptureFormat: ScreenCaptureFormat? = nil
    ) -> AutogeneratedSchemes {
        .workspace(
            AutogeneratedSchemeWorkspace(
                platform: platform,
                productFilters: productFilters,
                onlyFocusedTargets: onlyFocusedTargets,
                suffix: suffix,
                testActionArguments: testActionArguments,
                codeCoverageMode: codeCoverageMode,
                testingOptions: testingOptions,
                testLanguage: testLanguage,
                testRegion: testRegion,
                testScreenCaptureFormat: testScreenCaptureFormat
            )
        )
    }

    public static func allProjects(
        onlyFocusedTargets: Bool = true,
        suffix: String? = nil,
        exceptRegexps: [String] = [],
        testActionArguments: Arguments? = nil,
        runActionArguments: Arguments? = nil,
        targetSchemesGrouping: AutogeneratedSchemeProject.TargetSchemesGrouping = .byNameSuffix(
            build: ["Implementation", "Interface", "Mocks", "Testing"],
            test: ["Tests", "IntegrationTests", "UITests", "SnapshotTests"],
            run: ["App", "Demo", "Example"]
        ),
        codeCoverageEnabled: Bool = false,
        testingOptions: TestingOptions = [],
        testLanguage: SchemeLanguage? = nil,
        testRegion: String? = nil,
        testScreenCaptureFormat: ScreenCaptureFormat? = nil,
        runLanguage: SchemeLanguage? = nil,
        runRegion: String? = nil,
        testPlans: [String] = []
    ) -> AutogeneratedSchemes {
        .allProjects(
            AutogeneratedSchemeProject(
                onlyFocusedTargets: onlyFocusedTargets,
                suffix: suffix,
                exceptRegexps: exceptRegexps,
                testActionArguments: testActionArguments,
                runActionArguments: runActionArguments,
                targetSchemesGrouping: targetSchemesGrouping,
                codeCoverageEnabled: codeCoverageEnabled,
                testingOptions: testingOptions,
                testLanguage: testLanguage,
                testRegion: testRegion,
                testScreenCaptureFormat: testScreenCaptureFormat,
                runLanguage: runLanguage,
                runRegion: runRegion,
                testPlans: testPlans
            )
        )
    }

    public static func project(
        name: String,
        onlyFocusedTargets: Bool = true,
        suffix: String? = nil,
        exceptRegexps: [String] = [],
        testActionArguments: Arguments? = nil,
        runActionArguments: Arguments? = nil,
        targetSchemesGrouping: AutogeneratedSchemeProject.TargetSchemesGrouping = .byNameSuffix(
            build: ["Implementation", "Interface", "Mocks", "Testing"],
            test: ["Tests", "IntegrationTests", "UITests", "SnapshotTests"],
            run: ["App", "Demo", "Example"]
        ),
        codeCoverageEnabled: Bool = false,
        testingOptions: TestingOptions = [],
        testLanguage: SchemeLanguage? = nil,
        testRegion: String? = nil,
        testScreenCaptureFormat: ScreenCaptureFormat? = nil,
        runLanguage: SchemeLanguage? = nil,
        runRegion: String? = nil,
        testPlans: [String] = []
    ) -> AutogeneratedSchemes {
        .project(
            projectName: name,
            AutogeneratedSchemeProject(
                onlyFocusedTargets: onlyFocusedTargets,
                suffix: suffix,
                exceptRegexps: exceptRegexps,
                testActionArguments: testActionArguments,
                runActionArguments: runActionArguments,
                targetSchemesGrouping: targetSchemesGrouping,
                codeCoverageEnabled: codeCoverageEnabled,
                testingOptions: testingOptions,
                testLanguage: testLanguage,
                testRegion: testRegion,
                testScreenCaptureFormat: testScreenCaptureFormat,
                runLanguage: runLanguage,
                runRegion: runRegion,
                testPlans: testPlans
            )
        )
    }
}
