import Foundation

/// A project representation.
///
/// A project manifest needs to be defined in a `Project.swift` manifest file.
/// Manifests need to import the framework ProjectDescription which contains all
/// the classes and enums that are available for you to describe your projects.
///
/// The snippet below shows an example project manifest:
///
/// ```swift
/// import ProjectDescription
///
/// let project = Project(
///     name: "MyProject",
///     organizationName: "MyOrg",
///     targets: [
///         Target(
///             name: "App",
///             platform: .iOS,
///             product: .app,
///             bundleId: "io.geko.App",
///             infoPlist: "Config/App-Info.plist",
///             sources: ["Sources/**"],
///             resources: [
///                 "Resources/**",
///                 .folderReference(path: "Stubs"),
///                 .folderReference(path: "ODR", tags: ["odr_tag"])
///             ],
///             headers: .headers(
///                 public: ["Sources/public/A/**", "Sources/public/B/**"],
///                 private: "Sources/private/**",
///                 project: ["Sources/project/A/**", "Sources/project/B/**"]
///             ),
///             dependencies: [
///                 .project(target: "Framework1", path: "../Framework1"),
///                 .project(target: "Framework2", path: "../Framework2")
///             ]
///         )
///     ],
///     schemes: [
///         Scheme(
///             name: "App-Debug",
///             shared: true,
///             buildAction: .buildAction(targets: ["App"]),
///             testAction: .targets(["AppTests"]),
///             runAction: .runAction(executable: "App")
///         ),
///         Scheme(
///             name: "App-Release",
///             shared: true,
///             buildAction: .buildAction(targets: ["App"]),
///             runAction: .runAction(executable: "App")
///         )
///     ],
///     additionalFiles: [
///         "Dangerfile.swift",
///         "Documentation/**",
///         .folderReference(path: "Website")
///     ]
/// )
/// ```
public struct Project: Codable, Hashable {
    /// The name of the project. Also, the file name of the generated Xcode project.
    public var name: String
    /// The name of the organization used by Xcode as copyright.
    public var organizationName: String?
    /// The project options.
    public var options: Options
    /// The targets of the project.
    public var targets: [Target]
    /// The custom schemes for the project. Default schemes for each target are generated by default.
    public var schemes: [Scheme]
    /// The build settings and configuration for the project.
    public var settings: Settings
    /// The custom file header template for Xcode built-in file templates.
    public var fileHeaderTemplate: FileHeaderTemplate?
    /// The additional files for the project. For target's additional files, see ``Target/additionalFiles``.
    public var additionalFiles: [FileElement]

    // MARK: - Internal
    
    /// Project type indicating how the project will be initialized
    @frozen
    public enum ProjectType: Codable, Equatable {
        case geko
        case spm
        case cocoapods
    }

    /// Path to the folder that contains the project manifest.
    public var path: AbsolutePath

    /// Path to the root of the project sources.
    public var sourceRootPath: AbsolutePath

    /// Path to the Xcode project that will be generated.
    public var xcodeProjPath: AbsolutePath

    /// Path to podspec. Not nil if the project was generated from podspec.
    public var podspecPath: AbsolutePath?

    /// The group to place project files within
    public var filesGroup: ProjectGroup

    /// The version in which a check happened related to recommended settings after updating Xcode.
    public var lastUpgradeCheck: Version?

    /// Indicates whether the project is imported through `Dependencies.swift`.
    public var isExternal: Bool
    
    /// Indicates the initialization type of this project
    public var projectType: ProjectType

    public init(
        name: String,
        organizationName: String? = nil,
        options: Options = .options(),
        settings: Settings = .default,
        targets: [Target] = [],
        schemes: [Scheme] = [],
        fileHeaderTemplate: FileHeaderTemplate? = nil,
        additionalFiles: [FileElement] = []
    ) {
        self.name = name
        self.organizationName = organizationName
        self.options = options
        self.targets = targets
        self.schemes = schemes
        self.settings = settings
        self.additionalFiles = additionalFiles
        self.fileHeaderTemplate = fileHeaderTemplate

        // Internal
        path = "/"
        sourceRootPath = "/"
        xcodeProjPath = "/"
        isExternal = false
        filesGroup = .group(name: "Project")
        projectType = .geko

        dumpIfNeeded(self)
    }

    // MARK: - Hashable

    public func hash(into hasher: inout Hasher) {
        hasher.combine(path)
    }
}
