import Foundation

/// A test plan to run in a test action.
///
/// A test plan can reference an existing `.xctestplan` file on disk (``file``) or be declared
/// declaratively and generated by Geko (``generated``).
@frozen
public enum TestPlan: Hashable, Codable {
    /// Reference an existing `.xctestplan` file on disk.
    ///
    /// - Parameters:
    ///   - name: Name of the test plan.
    ///   - path: Path to the existing `.xctestplan` file.
    ///   - testTargets: Testable targets the plan runs.
    ///   - isDefault: Whether this is the default plan.
    case file(
        name: String,
        path: FilePath,
        testTargets: [TestableTarget],
        isDefault: Bool,
    )

    /// Describe a test plan that Geko generates during generation.
    case generated(GeneratedTestPlan)

    /// The name of the test plan.
    public var name: String {
        switch self {
        case let .file(name, _, _, _):
            name
        case let .generated(plan):
            plan.name
        }
    }

    /// The path of the test plan.
    public var path: FilePath {
        switch self {
        case let .file(_, path, _, _):
            path
        case let .generated(plan):
            plan.path
        }
    }

    /// The testable targets the test plan runs.
    public var testTargets: [TestableTarget] {
        switch self {
        case let .file(_, _, testTargets, _):
            testTargets
        case let .generated(plan):
            plan.testTargets.map { $0.target }
        }
    }

    /// Whether this is the default test plan.
    public var isDefault: Bool {
        switch self {
        case let .file(_, _, _, isDefault):
            isDefault
        case let .generated(plan):
            plan.isDefault
        }
    }

    /// Whether this test plan is generated by Geko rather than referencing an existing file.
    public var isGenerated: Bool {
        switch self {
        case .file: false
        case .generated: true
        }
    }

    @available(*, deprecated)
    public init(path: FilePath, testTargets: [TestableTarget], isDefault: Bool) {
        self = .file(
            name: path.basenameWithoutExt,
            path: path,
            testTargets: testTargets,
            isDefault: isDefault
        )
    }

    /// Creates a test plan that references an existing `.xctestplan` file on disk.
    ///
    /// - Parameters:
    ///   - path: Path to the existing `.xctestplan` file.
    ///   - testTargets: Testable targets the plan runs.
    ///   - isDefault: Whether this is the default plan.
    public static func file(
        path: FilePath,
        testTargets: [TestableTarget],
        isDefault: Bool
    ) -> Self {
        .file(
            name: path.basenameWithoutExt,
            path: path,
            testTargets: testTargets,
            isDefault: isDefault
        )
    }

    /// Creates a test plan that Geko generates during generation.
    ///
    /// - Parameters:
    ///   - name: Name of the generated test plan.
    ///   - directory: Directory the test plan is written to. If `nil`, it's written to the derived directory.
    ///   - configurations: Configurations of the generated test plan.
    ///   - defaultOptions: Default options applied to the generated test plan.
    ///   - testTargets: Explicit test targets to include in the generated test plan.
    ///   - targetSelection: Scopes that resolve which test targets to include in the generated test plan.
    ///   - isDefault: Whether this is the default plan.
    ///   - missingTargetPolicy: Policy applied when a target referenced by the generated test plan is missing.
    public static func generated(
        name: String,
        directory: FilePath? = nil,
        configurations: [GeneratedTestPlan.Configuration] = [],
        defaultOptions: GeneratedTestPlan.Options? = nil,
        testTargets: [GeneratedTestPlanTestableTarget] = [],
        targetSelection: [TestableTargetSelectionScope] = [],
        isDefault: Bool = false,
        missingTargetPolicy: GeneratedTestPlan.MissingTargetPolicy = .skipTestPlan()
    ) -> Self {
        .generated(
            GeneratedTestPlan(
                name: name,
                directory: directory,
                configurations: configurations,
                defaultOptions: defaultOptions,
                testTargets: testTargets,
                targetSelection: targetSelection,
                isDefault: isDefault,
                missingTargetPolicy: missingTargetPolicy
            )
        )
    }
}
