import Foundation

/// A workspace representation.
///
/// By default, `geko generate` generates an Xcode workspace that has the same name as the current project.
/// It includes the project and all its dependencies.
///
/// Geko allows customizing this behaviour by defining a workspace manifest within a `Workspace.swift` file.
///
/// Workspace manifests allow specifying a list of projects to generate and include in an Xcode workspace.
/// Those projects don’t necessarily have to depend on one another.
/// Additionally, files and folder references _(such as documentation files)_ can be included in a workspace manifest.
///
/// The snippet below shows an example workspace manifest:
///
/// ```swift
/// import ProjectDescription
///
/// let workspace = Workspace(
///     name: "Workspace",
///     projects: ["Projects/**"]
/// )
/// ```

public struct Workspace: Codable, Equatable {
    /// The name of the workspace. Also, the file name of the generated Xcode workspace.
    public var name: String

    /// The paths (or glob patterns) to manifest projects.
    public var projects: [FilePath]

    /// The custom schemes for the workspace. Default schemes for each target are generated by default.
    public var schemes: [Scheme]

    /// The custom file header template for Xcode built-in file templates.
    public var fileHeaderTemplate: FileHeaderTemplate?

    /// The additional files for the workspace. For project's additional files, see ``Project/additionalFiles``.
    public var additionalFiles: [FileElement]

    /// The generation configuration of the workspace.
    public var generationOptions: GenerationOptions

    /// The workspace mappers from plugins.
    public var workspaceMappers: [WorkspaceMapper]

    // MARK: Internal

    /// Path to where the manifest / root directory of this workspace is located
    public var path: AbsolutePath
    /// Path to where the `.xcworkspace` will be generated
    public var xcWorkspacePath: AbsolutePath

    public init(
        name: String,
        projects: [FilePath],
        schemes: [Scheme] = [],
        fileHeaderTemplate: FileHeaderTemplate? = nil,
        additionalFiles: [FileElement] = [],
        generationOptions: GenerationOptions = .options(),
        workspaceMappers: [WorkspaceMapper] = []
    ) {
        self.name = name
        self.projects = projects
        self.schemes = schemes
        self.fileHeaderTemplate = fileHeaderTemplate
        self.additionalFiles = additionalFiles
        self.generationOptions = generationOptions
        self.workspaceMappers = workspaceMappers

        // Internal
        path = "@/"
        xcWorkspacePath = "@/"

        dumpIfNeeded(self)
    }
}
