import Foundation

/// Common settings that can be shared across all or some modules.
public struct CommonSettings: Codable, Equatable, ExpressibleByDictionaryLiteral {
    /// Settings in format "Setting name": "Settings Value"
    public let settings: [String: SettingValue]
    /// Regular expression which describes which targets settings need to be applied to.
    public let targetMask: String?
    public let exceptMask: String?
    public let configurations: [String]

    public init(
        settings: [String: SettingValue],
        configurations: [String] = [],
        targetMask: String? = nil,
        exceptMask: String? = nil
    ) {
        self.settings = settings
        self.targetMask = targetMask
        self.exceptMask = exceptMask
        self.configurations = configurations
    }

    public init(dictionaryLiteral elements: (String, SettingValue)...) {
        self.init(settings: Dictionary(uniqueKeysWithValues:elements))
    }
}

extension Workspace {
    /// Generation options allow customizing the generation of the Xcode workspace.
    public struct GenerationOptions: Codable, Equatable {
        /// Contains options for autogenerated workspace schemes
        @frozen
        public enum AutogeneratedWorkspaceSchemes: Codable, Equatable {
            /// Contains options for code coverage
            @frozen
            public enum CodeCoverageMode: Codable, Equatable {
                /// Gather code coverage data for all targets in workspace.
                case all
                /// Enable code coverage for targets that have enabled code coverage in any of schemes in workspace.
                case relevant
                /// Gather code coverage for specified target references.
                case targets([TargetReference])
                /// Do not gather code coverage data.
                case disabled
            }

            /// Geko will not automatically generate any schemes
            case disabled
            /// Geko will generate schemes with the associated testing options
            case enabled(
                codeCoverageMode: CodeCoverageMode = .disabled,
                testingOptions: TestingOptions = [],
                testLanguage: SchemeLanguage? = nil,
                testRegion: String? = nil,
                testScreenCaptureFormat: ScreenCaptureFormat? = nil
            )
        }

        // Contains options for autogenerated pods projects
        @frozen
        public enum AutogenerateLocalPodsProjects: Codable, Equatable {
            /// Do not generate projects for podspec
            case disabled
            /// Generate projects for podspec automaticly
            /// - parameters:
            ///     - first: globs for searching podspecs
            ///     - second: path to folder where shoud be generated projects
            case automatic([FilePath], FilePath? = nil)
            /// Generate projects for podspec manualy
            /// - parameters:
            ///     - first: map where key is path to podspec, value is path to generated project folder
            case manual([FilePath: FilePath])
        }

        /// Description for a shared test target
        public struct SharedTestTarget: Codable, Equatable {
            public let testsPattern: String
            public let except: String?
            public let use: [String]
            public let name: String
            public let count: Int
            public let needAppHost: Bool

            public static func generate(name: String, testsPattern: String, except: String? = nil, needAppHost: Bool = false, count: Int = 1) -> SharedTestTarget {
                return SharedTestTarget(
                    testsPattern: testsPattern,
                    except: except,
                    use: [],
                    name: name,
                    count: count,
                    needAppHost: needAppHost
                )
            }

            public static func use(_ host: String, testsPattern: String, except: String? = nil) -> SharedTestTarget {
                return .use([host], testsPattern: testsPattern, except: except)
            }

            public static func use(_ hosts: [String], testsPattern: String, except: String? = nil) -> SharedTestTarget {
                return SharedTestTarget(
                    testsPattern: testsPattern,
                    except: except,
                    use: hosts,
                    name: "",
                    count: 0,
                    needAppHost: false
                )
            }
        }

        // Description for a shared test targets
        public struct GenerateSharedTestTarget: Codable, Equatable {
            public let installTo: String
            public let targets: [SharedTestTarget]

            public init(installTo: String, targets: [SharedTestTarget]) {
                self.installTo = installTo
                self.targets = targets
            }
        }
        
        /// Contains options for local pods schemes autogeneration
        @frozen
        public enum AutogenerateLocalPodsSchemes: Codable, Equatable {
            /// Disabled autogeneration
            case disabled

            /// Enabled autogeneration
            ///
            /// - parameter testPlans: Array of globs to xctestplans
            case enabled(testPlans: [FilePath])
        }

        /// Enable or disable automatic generation of schemes by Xcode.
        public var enableAutomaticXcodeSchemes: Bool?

        /// Enable or disable automatic generation of `Workspace` schemes. If enabled, options to configure code coverage and test
        /// targets can be passed in via associated values.
        public var autogeneratedWorkspaceSchemes: AutogeneratedWorkspaceSchemes

        /// Allows to suppress warnings in Xcode about updates to recommended settings added in or below the specified Xcode
        /// version. The warnings appear when Xcode version has been upgraded.
        /// It is recommended to set the version option to Xcode's version that is used for development of a project, for example
        /// `.lastXcodeUpgradeCheck(Version(13, 0, 0))` for Xcode 13.0.0.
        public var lastXcodeUpgradeCheck: Version?

        /// Allows to render markdown files inside the workspace including an .xcodesamples.plist inside it.
        public var renderMarkdownReadme: Bool

        /// Allows to integrate local podspecs as projects
        public var autogenerateLocalPodsProjects: AutogenerateLocalPodsProjects
        
        /// Allow to autogenerate local podsschemes
        public var autogenerateLocalPodsSchemes: AutogenerateLocalPodsSchemes

        public let generateSharedTestTarget: GenerateSharedTestTarget?

        public let commonSettings: [CommonSettings]

        public var configurations: [String: BuildConfiguration.Variant]

        public init(
            enableAutomaticXcodeSchemes: Bool?,
            autogeneratedWorkspaceSchemes: AutogeneratedWorkspaceSchemes,
            lastXcodeUpgradeCheck: Version?,
            renderMarkdownReadme: Bool,
            autogenerateLocalPodsProjects: AutogenerateLocalPodsProjects,
            autogenerateLocalPodsSchemes: AutogenerateLocalPodsSchemes,
            generateSharedTestTarget: GenerateSharedTestTarget?,
            commonSettings: [CommonSettings],
            configurations: [String: BuildConfiguration.Variant]
        ) {
            self.enableAutomaticXcodeSchemes = enableAutomaticXcodeSchemes
            self.autogeneratedWorkspaceSchemes = autogeneratedWorkspaceSchemes
            self.lastXcodeUpgradeCheck = lastXcodeUpgradeCheck
            self.renderMarkdownReadme = renderMarkdownReadme
            self.autogenerateLocalPodsProjects = autogenerateLocalPodsProjects
            self.autogenerateLocalPodsSchemes = autogenerateLocalPodsSchemes
            self.generateSharedTestTarget = generateSharedTestTarget
            self.commonSettings = commonSettings
            self.configurations = configurations
        }

        public static func options(
            enableAutomaticXcodeSchemes: Bool? = false,
            autogeneratedWorkspaceSchemes: AutogeneratedWorkspaceSchemes = .enabled(),
            lastXcodeUpgradeCheck: Version? = nil,
            renderMarkdownReadme: Bool = false,
            autogenerateLocalPodsProjects: AutogenerateLocalPodsProjects = .disabled,
            autogenerateLocalPodsSchemes: AutogenerateLocalPodsSchemes = .disabled,
            generateSharedTestTarget: GenerateSharedTestTarget? = nil,
            commonSettings: [CommonSettings] = [],
            configurations: [String: BuildConfiguration.Variant] = ["Debug": .debug, "Release": .release]
        ) -> Self {
            GenerationOptions(
                enableAutomaticXcodeSchemes: enableAutomaticXcodeSchemes,
                autogeneratedWorkspaceSchemes: autogeneratedWorkspaceSchemes,
                lastXcodeUpgradeCheck: lastXcodeUpgradeCheck,
                renderMarkdownReadme: renderMarkdownReadme,
                autogenerateLocalPodsProjects: autogenerateLocalPodsProjects,
                autogenerateLocalPodsSchemes: autogenerateLocalPodsSchemes,
                generateSharedTestTarget: generateSharedTestTarget,
                commonSettings: commonSettings,
                configurations: configurations
            )
        }
    }
}
