import Foundation

/// Common settings that can be shared across all or some modules.
public struct CommonSettings: Codable, Equatable, ExpressibleByDictionaryLiteral {
    /// Settings in format "Setting name": "Settings Value"
    public let settings: [String: SettingValue]
    /// Regular expression which describes which targets settings need to be applied to.
    public let targetRegexp: String?
    /// Regular expression which describes which targets need to be excluded from applying settings.
    public let exceptRegexp: String?
    /// List of configuration names to apply settings to.
    public let configurations: [String]

    /// Creates a new `CommonSettings` instance.
    /// - Parameters:
    ///   - settings: settings that need to be applied
    ///   - configurations: list of configuration names
    ///   - targetRegexp: regular expression that will be mathched against target names
    ///   - exceptRegexp: regular expression exceptions that will be mathched against target names
    public init(
        settings: [String: SettingValue],
        configurations: [String] = [],
        targetRegexp: String? = nil,
        exceptRegexp: String? = nil
    ) {
        self.settings = settings
        self.targetRegexp = targetRegexp
        self.exceptRegexp = exceptRegexp
        self.configurations = configurations
    }

    public init(dictionaryLiteral elements: (String, SettingValue)...) {
        self.init(settings: Dictionary(uniqueKeysWithValues:elements))
    }
}

extension Workspace {
    /// Generation options allow customizing the generation of the Xcode workspace.
    public struct GenerationOptions: Codable, Equatable {
        /// Contains options for autogenerated workspace schemes
        @frozen
        public enum AutogeneratedWorkspaceSchemes: Codable, Equatable {
            /// Contains options for code coverage
            @frozen
            public enum CodeCoverageMode: Codable, Equatable {
                /// Gather code coverage data for all targets in workspace.
                case all
                /// Enable code coverage for targets that have enabled code coverage in any of schemes in workspace.
                case relevant
                /// Gather code coverage for specified target references.
                case targets([TargetReference])
                /// Do not gather code coverage data.
                case disabled
            }

            /// Geko will not automatically generate any schemes
            case disabled
            /// Geko will generate schemes with the associated testing options
            case enabled(
                codeCoverageMode: CodeCoverageMode = .disabled,
                testingOptions: TestingOptions = [],
                testLanguage: SchemeLanguage? = nil,
                testRegion: String? = nil,
                testScreenCaptureFormat: ScreenCaptureFormat? = nil
            )
        }

        // Contains options for autogenerated pods projects
        @frozen
        public enum AutogenerateLocalPodsProjects: Codable, Equatable {
            /// Do not generate projects for podspec
            case disabled
            /// Generate projects for podspec automaticly
            /// - parameters:
            ///     - first: globs for searching podspecs
            ///     - second: path to folder where projects shoud be generate
            case automatic([FilePath], FilePath? = nil)
            /// Generate projects for podspecs manualy
            /// - parameters:
            ///     - first: map where key is a path to podspec, value is a path to generated project folder
            case manual([FilePath: FilePath])
        }

        /// Contains options for local pods schemes autogeneration
        @frozen
        public enum AutogenerateLocalPodsSchemes: Codable, Equatable {
            /// Disabled autogeneration
            case disabled

            /// Enabled autogeneration
            ///
            /// - parameter testPlans: Array of globs to xctestplans
            case enabled(testPlans: [FilePath])
        }

        /// Enable or disable automatic generation of schemes by Xcode.
        public var enableAutomaticXcodeSchemes: Bool?

        /// Enable or disable automatic generation of `Workspace` schemes. If enabled, options to configure code coverage and test
        /// targets can be passed in via associated values.
        public var autogeneratedWorkspaceSchemes: AutogeneratedWorkspaceSchemes

        /// Allows to suppress warnings in Xcode about updates to recommended settings added in or below the specified Xcode
        /// version. The warnings appear when Xcode version has been upgraded.
        /// It is recommended to set the version option to Xcode's version that is used for development of a project, for example
        /// `.lastXcodeUpgradeCheck(Version(13, 0, 0))` for Xcode 13.0.0.
        public var lastXcodeUpgradeCheck: Version?

        /// Allows to render markdown files inside the workspace including an .xcodesamples.plist inside it.
        public var renderMarkdownReadme: Bool

        /// Allows to integrate local podspecs as projects
        public var autogenerateLocalPodsProjects: AutogenerateLocalPodsProjects

        /// Allow to autogenerate local podsschemes
        public var autogenerateLocalPodsSchemes: AutogenerateLocalPodsSchemes

        /// Applies settings across several projects
        public let commonSettings: [CommonSettings]

        /// Creates configurations for all projects
        public var configurations: [String: BuildConfiguration.Variant]

        public init(
            enableAutomaticXcodeSchemes: Bool?,
            autogeneratedWorkspaceSchemes: AutogeneratedWorkspaceSchemes,
            lastXcodeUpgradeCheck: Version?,
            renderMarkdownReadme: Bool,
            autogenerateLocalPodsProjects: AutogenerateLocalPodsProjects,
            autogenerateLocalPodsSchemes: AutogenerateLocalPodsSchemes,
            commonSettings: [CommonSettings],
            configurations: [String: BuildConfiguration.Variant]
        ) {
            self.enableAutomaticXcodeSchemes = enableAutomaticXcodeSchemes
            self.autogeneratedWorkspaceSchemes = autogeneratedWorkspaceSchemes
            self.lastXcodeUpgradeCheck = lastXcodeUpgradeCheck
            self.renderMarkdownReadme = renderMarkdownReadme
            self.autogenerateLocalPodsProjects = autogenerateLocalPodsProjects
            self.autogenerateLocalPodsSchemes = autogenerateLocalPodsSchemes
            self.commonSettings = commonSettings
            self.configurations = configurations
        }

        public static func options(
            enableAutomaticXcodeSchemes: Bool? = false,
            autogeneratedWorkspaceSchemes: AutogeneratedWorkspaceSchemes = .enabled(),
            lastXcodeUpgradeCheck: Version? = nil,
            renderMarkdownReadme: Bool = false,
            autogenerateLocalPodsProjects: AutogenerateLocalPodsProjects = .disabled,
            autogenerateLocalPodsSchemes: AutogenerateLocalPodsSchemes = .disabled,
            commonSettings: [CommonSettings] = [],
            configurations: [String: BuildConfiguration.Variant] = ["Debug": .debug, "Release": .release]
        ) -> Self {
            GenerationOptions(
                enableAutomaticXcodeSchemes: enableAutomaticXcodeSchemes,
                autogeneratedWorkspaceSchemes: autogeneratedWorkspaceSchemes,
                lastXcodeUpgradeCheck: lastXcodeUpgradeCheck,
                renderMarkdownReadme: renderMarkdownReadme,
                autogenerateLocalPodsProjects: autogenerateLocalPodsProjects,
                autogenerateLocalPodsSchemes: autogenerateLocalPodsSchemes,
                commonSettings: commonSettings,
                configurations: configurations
            )
        }
    }
}
